voorbeeld/config/routes.rb
Voorbeeld::Application.routes.draw do
  root :to => 'pages#home'
  resources :gebruikers
  resources :sessies
  match 'registreer' => 'gebruikers#new', :as => :registreer
  match 'login' => 'sessies#new', :as => :login
  match 'logout' => 'sessies#destroy', :as => :logout

end

voorbeeld/app/models/gebruiker.rb
class Gebruiker < ActiveRecord::Base
  attr_accessible :naam, :email, :wachtwoord
  attr_accessor :wachtwoord
  before_save :versleutel_wachtwoord

  validates :naam,  :presence => true
  validates :wachtwoord,  :presence => true, :length => {:minimum => 8}
  validates :email, :presence => true, :uniqueness => true,
                    :length => {:minimum => 3, :maximum => 254},
                    :uniqueness => true,
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}

  def self.authenticate(email, wachtwoord)
    gebruiker = find_by_email(email)
    if gebruiker
      versleuteld_wachtwoord = Digest::SHA1.hexdigest(wachtwoord+gebruiker.wachtwoord_salt)
      if gebruiker.wachtwoord_hash == versleuteld_wachtwoord
        gebruiker # geef record terug
      end
    end
  end

  def versleutel_wachtwoord
    if wachtwoord.present?
      self.wachtwoord_salt = rand(36**16).to_s(36)
      self.wachtwoord_hash = Digest::SHA1.hexdigest(wachtwoord+wachtwoord_salt)
    end
  end
end

voorbeeld/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :ingelogd

  private
  def ingelogd
    sessie = session[:gebruiker_id]
    @ingelogd ||= Gebruiker.find(sessie) if sessie
  end
end

voorbeeld/app/controllers/gebruikers_controller.rb
class GebruikersController < ApplicationController
  # GET /gebruikers
  # GET /gebruikers.json
  def index
    @gebruikers = Gebruiker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @gebruikers }
    end
  end

  # GET /gebruikers/1
  # GET /gebruikers/1.json
  def show
    @gebruiker = Gebruiker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @gebruiker }
    end
  end

  # GET /gebruikers/new
  # GET /gebruikers/new.json
  def new
    @gebruiker = Gebruiker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @gebruiker }
    end
  end

  # GET /gebruikers/1/edit
  def edit
    @gebruiker = Gebruiker.find(params[:id])
  end

  # POST /gebruikers
  # POST /gebruikers.json
  def create
    @gebruiker = Gebruiker.new(params[:gebruiker])

    respond_to do |format|
      if @gebruiker.save
        format.html { redirect_to @gebruiker, :notice => 'Gebruiker was successfully created.' }
        format.json { render :json => @gebruiker, :status => :created, :location => @gebruiker }
      else
        format.html { render :action => "new" }
        format.json { render :json => @gebruiker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gebruikers/1
  # PUT /gebruikers/1.json
  def update
    @gebruiker = Gebruiker.find(params[:id])

    respond_to do |format|
      if @gebruiker.update_attributes(params[:gebruiker])
        format.html { redirect_to @gebruiker, :notice => 'Gebruiker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @gebruiker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gebruikers/1
  # DELETE /gebruikers/1.json
  def destroy
    @gebruiker = Gebruiker.find(params[:id])
    @gebruiker.destroy

    respond_to do |format|
      format.html { redirect_to gebruikers_url }
      format.json { head :no_content }
    end
  end
end

voorbeeld/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

voorbeeld/app/controllers/sessies_controller.rb
class SessiesController < ApplicationController
  def new
  end

  def create
    gebruiker = Gebruiker.authenticate(params[:email], params[:wachtwoord])

    respond_to do |format|
      if gebruiker
        session[:gebruiker_id] = gebruiker.id
        format.html { redirect_to root_url, :notice => "Ingelogd" }
#        format.json { head :no_content }
      else
        format.html { redirect_to "/login", :notice => "Incorrect wachtwoord"}
#        format.json { head :no_content }
      end
    end
  end

  def destroy
    session[:gebruiker_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, :notice => "Uitgelogd!" }
#     format.json { head :no_content }
    end
  end
end

voorbeeld/app/helpers/application_helper.rb
module ApplicationHelper
end

voorbeeld/app/helpers/gebruikers_helper.rb
module GebruikersHelper
end

voorbeeld/app/helpers/pages_helper.rb
module PagesHelper
end

voorbeeld/app/helpers/sessies_helper.rb
module SessiesHelper
end

voorbeeld/app/views/gebruikers/_form.html.erb
<%= form_for(@gebruiker) do |f| %>
  <% if @gebruiker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gebruiker.errors.count, "error") %> prohibited this gebruiker from being saved:</h2>

      <ul>
      <% @gebruiker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :naam %><br />
    <%= f.text_field :naam %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :wachtwoord %><br />
    <%= f.password_field :wachtwoord %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

voorbeeld/app/views/gebruikers/edit.html.erb
<h1>Editing gebruiker</h1>

<%= render 'form' %>

<%= link_to 'Show', @gebruiker %> |
<%= link_to 'Back', gebruikers_path %>

voorbeeld/app/views/gebruikers/index.html.erb
<h1>Listing gebruikers</h1>

<table>
  <tr>
    <th>Naam</th>
    <th>Email</th>
    <th>Wachtwoord hash</th>
    <th>Wachtwoord salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gebruikers.each do |gebruiker| %>
  <tr>
    <td><%= gebruiker.naam %></td>
    <td><%= gebruiker.email %></td>
    <td><%= gebruiker.wachtwoord_hash %></td>
    <td><%= gebruiker.wachtwoord_salt %></td>
    <td><%= link_to 'Show', gebruiker %></td>
    <td><%= link_to 'Edit', edit_gebruiker_path(gebruiker) %></td>
    <td><%= link_to 'Destroy', gebruiker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gebruiker', new_gebruiker_path %>

voorbeeld/app/views/gebruikers/new.html.erb
<h1>New gebruiker</h1>

<%= render 'form' %>

<%= link_to 'Back', gebruikers_path %>

voorbeeld/app/views/gebruikers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Naam:</b>
  <%= @gebruiker.naam %>
</p>

<p>
  <b>Email:</b>
  <%= @gebruiker.email %>
</p>

<p>
  <b>Wachtwoord hash:</b>
  <%= @gebruiker.wachtwoord_hash %>
</p>

<p>
  <b>Wachtwoord salt:</b>
  <%= @gebruiker.wachtwoord_salt %>
</p>


<%= link_to 'Edit', edit_gebruiker_path(@gebruiker) %> |
<%= link_to 'Back', gebruikers_path %>

voorbeeld/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voorbeeld</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="navigatie">
	<% if ingelogd %>
	Ingelogd als <%= ingelogd.naam %> |
	<%= link_to "Uitloggen", logout_path %>
	<% else %>
	<%= link_to "Registreren", registreer_path %> of 
	<%= link_to "Inloggen", login_path %>
	<% end %>
</div>

<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

voorbeeld/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

voorbeeld/app/views/sessies/create.html.erb
<h1>Sessies#create</h1>
<p>Find me in app/views/sessies/create.html.erb</p>

voorbeeld/app/views/sessies/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Login</h1>

<%= form_tag sessies_path  do %>
  <p>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </p>
  <p>
    <%= label_tag :wachtwoord %><br />
    <%= password_field_tag :wachtwoord %>
  </p>
  <p class="button"><%= submit_tag %></p>
<% end %>